### ISSUE TITLE
Copy-paste?

### ISSUE THREAD

**Issue by Suntrie** [filrech/tar-utility#4]
Дополнительных пояснений требует совпадение структуры решения с Артемом Ивашкиным и одинаковых недочетов.

**Comment by filrech** [comment]
Я действительно пробегался по **всем** вами открытым вопросам (Issues), чтобы избежать типовых ошибок. Код и структуру решения я не заимствовал (по крайней мере не с Артема). 
Список почти всех (кроме тех ссылок, которые давали вы) ресурсов , которыми я пользовался:
https://memorynotfound.com/java-tar-example-compress-decompress-tar-tar-gz-files/
https://stackoverflow.com/questions/26552624/how-to-merge-data-from-two-text-file
https://javabeat.net/java-split-merge-files/
https://www.geeksforgeeks.org/java-program-to-merge-contents-of-all-the-files-in-a-directory/
https://www.geeksforgeeks.org/java-program-merge-two-files-alternatively-third-file-2/
https://habr.com/ru/post/496290/
https://www.cyberforum.ru/java-j2se/thread706935.html
https://www.cyberforum.ru/cmd-bat/thread833365.html
https://stackoverflow.com/questions/16665124/java-how-to-append-text-to-top-of-file-txt

**Comment by Suntrie** [comment]
Поняла, разумно, принято.
